CREATE TABLE user_accounts (
	user_id INT AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255),
	password TEXT,
	is_admin TINYINT(1) NOT NULL DEFAULT 0,
	is_suspended TINYINT(1) NOT NULL DEFAULT 0,
	date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);


CREATE TABLE job_postings (
	job_id INT AUTO_INCREMENT PRIMARY KEY,
	job_title VARCHAR(255),
	status VARCHAR(255),
	date_added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)